Razor_Pages_Project/Pages/Employees/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Razor_Pages_Project.Models;
using Razor_Pages_Project.Services;

namespace Razor_Pages_Project.Pages.Employees
{
    public class DeleteModel : PageModel
    {
        private readonly IEmployeeRepository employeeRepository;

        public DeleteModel(IEmployeeRepository employeeRepository)
        {
            this.employeeRepository = employeeRepository;
        }

        [BindProperty]
        public Employee Employee { get; set; }
        public IActionResult OnGet(int id)
        {
            Employee = employeeRepository.GetEmployee(id);

            if(Employee == null)
            {
                return RedirectToPage("/NotFound");
            }
            else
            {
                return Page();
           }

        }

        public IActionResult OnPost()
        {
          Employee  DeletedEmployee = employeeRepository.Delete(Employee.Id);

            if(DeletedEmployee == null)
            {
                return RedirectToPage("/NotFound");
            }
           
                return RedirectToPage("Index");
           

        }
    }
}

Razor_Pages_Project/Pages/Employees/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Razor_Pages_Project.Models;
using Razor_Pages_Project.Services;

namespace Razor_Pages_Project.Pages.Employees
{
    public class DetailsModel : PageModel
    {
        private readonly IEmployeeRepository employeeRepository;


        public DetailsModel(IEmployeeRepository employeeRepository)
        {
            this.employeeRepository = employeeRepository;
        }

        public Employee Employee { get; private set; }

        [TempData]
        public string Message { get; set; }
        public IActionResult OnGet( int ID)
        {

            Employee = employeeRepository.GetEmployee(ID);
            if(Employee == null)
            {
                return RedirectToPage("/NotFound");
            }

            return Page();
        }
    }
}

Razor_Pages_Project/Pages/Employees/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Razor_Pages_Project.Models;
using Razor_Pages_Project.Services;

namespace Razor_Pages_Project.Pages.Employees
{
    public class EditModel : PageModel
    {
        private readonly IEmployeeRepository employeeRepository;
        private readonly IWebHostEnvironment webHostEnvironment;

        public EditModel(IEmployeeRepository employeeRepository,
                IWebHostEnvironment webHostEnvironment)
        {
            this.employeeRepository = employeeRepository;
            this.webHostEnvironment = webHostEnvironment;
        }


        [BindProperty]
        public bool Notify { get; set; }

        public string Message { get; set; }

        [BindProperty]
        public Employee Employee { get; set; }

        [BindProperty]
        public IFormFile Photo { get; set; }

        public IActionResult OnGet(int? id)
        {
            if(id.HasValue)
            { 
            Employee = employeeRepository.GetEmployee(id.Value);
            }
            else
            {
                Employee = new Employee();
            }
            if (Employee == null)
            {
                return RedirectToPage("/NotFound");
            }

            return Page();
        }


        public IActionResult OnPost()
        {
            if (ModelState.IsValid)
            {
                if (Photo != null)
                {
                    if (Employee.PhotoPath != null)
                    {
                        string filePath = Path.Combine(webHostEnvironment.WebRootPath,
                            "images", Employee.PhotoPath);
                        System.IO.File.Delete(filePath);
                    }
                    Employee.PhotoPath = ProcessUploadedFile();
                }
                if (Employee.Id > 0)
                {
                    Employee = employeeRepository.Update(Employee);
                }
                else
                {
                    Employee = employeeRepository.Add(Employee);
                }
                return RedirectToPage("Index");
            }

            return Page();
        }

        public IActionResult OnPostUpdateNotificationPreferences(int id)
        {
            if (Notify)
            {
                Message = "Thank you for turning on notifications";
            }
            else
            {
                Message = "You have turned off email notifications";
            }

            TempData["message"] = Message;
            return RedirectToPage("Details", new { id = id });
        }
        private string ProcessUploadedFile()
        {
            string uniqueFileName = null;

            if (Photo != null)
            {
                string uploadsFolder = Path.Combine(webHostEnvironment.WebRootPath, "images");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + Photo.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    Photo.CopyTo(fileStream);
                }
            }

            return uniqueFileName;
        }
    }
}

Razor_Pages_Project/Pages/Employees/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Razor_Pages_Project.Models;
using Razor_Pages_Project.Services;

namespace Razor_Pages_Project.Pages.Employees
{
    public class IndexModel : PageModel
    {
        private readonly IEmployeeRepository employeeRepository;

        public IEnumerable<Employee> Employees { get; set; }

        [BindProperty(SupportsGet =true)]
        public string SearchTerm { get; set; }
        public IndexModel(IEmployeeRepository employeeRepository)
        {
            this.employeeRepository = employeeRepository;
        }
        public void OnGet()
        {
            Employees = employeeRepository.Search(SearchTerm);

        }
    }
}

Razor_Pages_Project/ViewComponents/HeadCountViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Razor_Pages_Project.Models;
using Razor_Pages_Project.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Razor_Pages_Project.ViewComponents
{
    public class HeadCountViewComponent : ViewComponent
    {
        private readonly IEmployeeRepository employeeRepository;

        public HeadCountViewComponent(IEmployeeRepository employeeRepository)
        {
            this.employeeRepository = employeeRepository;
        }

        public IViewComponentResult Invoke(Dept? departmentName =null)
        {
            var result = employeeRepository.EmployeeCountByDepartment(departmentName);
            return View(result);
        }
    }
}

Razor_Pages_Project/Pages/Employees/Delete.cshtml
@page "{id}"
@model Razor_Pages_Project.Pages.Employees.DeleteModel
@{
    ViewData["Title"] = "Delete";
    ViewData["ShowButton"] = false;
}

<h1>Delete Confirmation</h1>

<div class="alert alert-danger">
    <partial name="_DisplayEmployeePartial" model="Model.Employee" view-data="ViewData" />
    <h5>Are You sure You Want Delete Employee  - @Model.Employee.Name</h5>
    <form method="post">
        <button type="submit" class="btn btn-danger">Yes</button>
        <a class="btn btn-primary" asp-page="/Employees/Index">No</a>
    </form>
</div>

Razor_Pages_Project/Pages/Employees/Details.cshtml
@page "/Employees/View/{ID:min(1)}"
@model Razor_Pages_Project.Pages.Employees.DetailsModel
@{
    ViewData["Title"] = "Details";
    var photoPath = "~/images/" + (Model.Employee.PhotoPath ?? "Anonymous.jpg");
}



    <div class="row justify-content-center m-3">

        @if (Model.Message != null)
        {
            <div class="col-sm-8">
                <div class="alert alert-primary">
                    @Model.Message
                </div>
            </div>
        }

        <div class="col-sm-8">
            @*@await Component.InvokeAsync("HeadCount",new { department = Model.Employee.Department})*@
            <vc:head-count department-name="@Model.Employee.Department"></vc:head-count> 
        </div>
        <div class="col-sm-8">
            <div class="card">
                <div class="card-header">
                    <h1>@Model.Employee.Name</h1>
                </div>

                <div class="card-body text-center">
                    <img class="card-img-top" src="@photoPath" asp-append-version="true" />

                    <h4>Employee ID : @Model.Employee.Id</h4>
                    <h4>Email : @Model.Employee.Email</h4>
                    <h4>Department : @Model.Employee.Department</h4>

                </div>
                <div class="card-footer text-center">
                    <a asp-page="index"
                       class="btn btn-primary">Back</a>
                    <a href="#" class="btn btn-primary">Edit</a>
                    <a href="#" class="btn btn-danger">Delete</a>
                </div>
            </div>
        </div>
    </div>

Razor_Pages_Project/Pages/Employees/Edit.cshtml
@page "{Id:min(1)?}/{handler?}"
@model Razor_Pages_Project.Pages.Employees.EditModel
@{
    ViewData["Title"] = "Edit";
    var photoPath = "~/images/" + (Model.Employee.PhotoPath ?? "Anonymous.jpg");
    var PageHeader = Model.Employee.Id > 0 ? "Edit" : "Create";
}


<h1>Notification Preferences</h1>

<form method="post" asp-page-handler="UpdateNotificationPreferences">
    <div class="form-check">
        <input asp-for="Notify" class="form-check-input" />
        <label asp-for="Notify" class="form-check-label">
            Receive email notification when my details change
        </label>
    </div>
    <button type="submit" class="btn btn-primary">
        Update Notification Preferences
    </button>
   
</form>

<hr />
<h1>@PageHeader</h1>
<form method="post" class="m-3" enctype="multipart/form-data"   asp-page-handler="OnPost">

    <input hidden asp-for="Employee.Id" />
    <input hidden asp-for="Employee.PhotoPath" />

    <div asp-validation-summary="All" class="text-danger"></div>

    <div class="form-group row">
        <label asp-for="Employee.Name" class="col-sm-2 col-form-label">
        </label>
        <div class="col-sm-10">
            <input asp-for="Employee.Name" class="form-control" placeholder="Name">
            <span asp-validation-for="Employee.Name" class="text-danger"></span>
            
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="Employee.Email" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Employee.Email" class="form-control" placeholder="Email">
            <span asp-validation-for="Employee.Email" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group row">
        <label asp-for="Employee.Department" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <select asp-for="Employee.Department" class="custom-select mr-sm-2"
                    asp-items="Html.GetEnumSelectList<Dept>()">
                <option value="">Please Select</option>
            </select>
            <span asp-validation-for="Employee.Department" class="text-danger"></span>

        </div>
    </div>

    <div class="form-group row">
        <label asp-for="Photo" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <div class="custom-file">
                <input asp-for="Photo" class="custom-file-input form-control">
                <label class="custom-file-label">Click here to change photo</label>
            </div>
        </div>
    </div>

    <div class="form-group row col-sm-4 offset-4">
        <img class="imageThumbnail" src="@photoPath" asp-append-version="true" />
    </div>
    <div class="form-group row">
        <div class="col-sm-10">
            <button type="submit" class="btn btn-primary">Save</button>
            <a asp-page="/Employees/Index" class="btn btn-primary">Cancel</a>
        </div>
    </div>

    @section Scripts {
        <script>
            $(document).ready(function () {
                $('.custom-file-input').on("change", function () {
                    var fileName = $(this).val().split("\\").pop();
                    $(this).next('.custom-file-label').html(fileName);
                });
            });
        </script>

    <partial name="_ValidationScriptsPartial"/>
    }
</form>

Razor_Pages_Project/Pages/Employees/Index.cshtml
@page
@model Razor_Pages_Project.Pages.Employees.IndexModel
@{
    ViewData["Title"] = "Index";
    ViewData["ShowButton"] = true;
}

<style>
    .btn {
        width: 75px;
    }
</style>
<form method="get">
    <div class="input-group" >
        <input class="form-control"asp-for="SearchTerm" />
        <div class="input-group-append">
            <button type="submit" class="btn btn-primary">search</button>
        </div>
    </div>

</form>

@*@await Component.InvokeAsync("HeadCount" )*@
<vc:head-count department-name="@null"></vc:head-count>
<h1>Employees</h1>

<div class="card-deck">
    @foreach (var Employee in Model.Employees)
    {
        <partial name="_DisplayEmployeePartial" model="Employee" view-data="ViewData" />

    }

</div>